//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources.Domain {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Tables {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Tables() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources.Domain.Tables", typeof(Tables).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Additional topping.
        /// </summary>
        public static string AdditionalTopping {
            get {
                return ResourceManager.GetString("AdditionalTopping", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Additional toppings.
        /// </summary>
        public static string AdditionalToppings {
            get {
                return ResourceManager.GetString("AdditionalToppings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cart.
        /// </summary>
        public static string Cart {
            get {
                return ResourceManager.GetString("Cart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Carts.
        /// </summary>
        public static string Carts {
            get {
                return ResourceManager.GetString("Carts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Crust.
        /// </summary>
        public static string Crust {
            get {
                return ResourceManager.GetString("Crust", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Crusts.
        /// </summary>
        public static string Crusts {
            get {
                return ResourceManager.GetString("Crusts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Default topping.
        /// </summary>
        public static string DefaultTopping {
            get {
                return ResourceManager.GetString("DefaultTopping", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Default toppings.
        /// </summary>
        public static string DefaultToppings {
            get {
                return ResourceManager.GetString("DefaultToppings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Drink.
        /// </summary>
        public static string Drink {
            get {
                return ResourceManager.GetString("Drink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Drink in cart.
        /// </summary>
        public static string DrinkInCart {
            get {
                return ResourceManager.GetString("DrinkInCart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Drinks in carts.
        /// </summary>
        public static string DrinkInCarts {
            get {
                return ResourceManager.GetString("DrinkInCarts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Drinks.
        /// </summary>
        public static string Drinks {
            get {
                return ResourceManager.GetString("Drinks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Incoice.
        /// </summary>
        public static string Invoice {
            get {
                return ResourceManager.GetString("Invoice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invoice line.
        /// </summary>
        public static string InvoiceLine {
            get {
                return ResourceManager.GetString("InvoiceLine", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invoice lines.
        /// </summary>
        public static string InvoiceLines {
            get {
                return ResourceManager.GetString("InvoiceLines", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invoices.
        /// </summary>
        public static string Invoices {
            get {
                return ResourceManager.GetString("Invoices", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Owner.
        /// </summary>
        public static string Owner {
            get {
                return ResourceManager.GetString("Owner", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Party order.
        /// </summary>
        public static string PartyOrder {
            get {
                return ResourceManager.GetString("PartyOrder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Party order invoice.
        /// </summary>
        public static string PartyOrderInvoice {
            get {
                return ResourceManager.GetString("PartyOrderInvoice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Party orders&apos; invoices.
        /// </summary>
        public static string PartyOrderInvoices {
            get {
                return ResourceManager.GetString("PartyOrderInvoices", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Party orders.
        /// </summary>
        public static string PartyOrders {
            get {
                return ResourceManager.GetString("PartyOrders", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pizza in cart.
        /// </summary>
        public static string PizzaInCart {
            get {
                return ResourceManager.GetString("PizzaInCart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pizzas in carts.
        /// </summary>
        public static string PizzaInCarts {
            get {
                return ResourceManager.GetString("PizzaInCarts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pizza type.
        /// </summary>
        public static string PizzaType {
            get {
                return ResourceManager.GetString("PizzaType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pizza types.
        /// </summary>
        public static string PizzaTypes {
            get {
                return ResourceManager.GetString("PizzaTypes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Size.
        /// </summary>
        public static string Size {
            get {
                return ResourceManager.GetString("Size", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sizes.
        /// </summary>
        public static string Sizes {
            get {
                return ResourceManager.GetString("Sizes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Topping.
        /// </summary>
        public static string Topping {
            get {
                return ResourceManager.GetString("Topping", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Toppings.
        /// </summary>
        public static string Toppings {
            get {
                return ResourceManager.GetString("Toppings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Transport.
        /// </summary>
        public static string Transport {
            get {
                return ResourceManager.GetString("Transport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Transports.
        /// </summary>
        public static string Transports {
            get {
                return ResourceManager.GetString("Transports", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User.
        /// </summary>
        public static string User {
            get {
                return ResourceManager.GetString("User", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Users.
        /// </summary>
        public static string Users {
            get {
                return ResourceManager.GetString("Users", resourceCulture);
            }
        }
    }
}
